### ISSUE TITLE
向dalao请教使用方法

### ISSUE THREAD

**Issue by RMBDRAGON** [ccjjfdyqlhy/.lpk_file_unpacker#2]
![image](https://user-images.githubusercontent.com/115329559/209135706-9edb5db2-4dc1-4425-9f63-02335ab60772.png)
按README输入上述指令但是cmd没有任何回应，也确认没有执行解包，不知道是我输入有问题还是因为什么，我是直接在lpk.exe所在目录cmd，然后输入的。

**Comment by ccjjfdyqlhy** [comment]
试试用相对路径：把lpk.exe移动到含有lpk文件和config.json的目录下，再使用  
**>./lpk.exe ./2218059121.lpk ./OUTPUT ./config.json**  
有可能是跨文件夹传导文件的问题。即将在不久后使用图形界面，这样就更方便操作一点。
